//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CV_Udemy.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CV_SiteEntities : DbContext
    {
        public CV_SiteEntities()
            : base("name=CV_SiteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_About> TBL_About { get; set; }
        public virtual DbSet<TBL_Admin> TBL_Admin { get; set; }
        public virtual DbSet<TBL_Certificate> TBL_Certificate { get; set; }
        public virtual DbSet<TBL_Contact> TBL_Contact { get; set; }
        public virtual DbSet<TBL_Education> TBL_Education { get; set; }
        public virtual DbSet<TBL_Experience> TBL_Experience { get; set; }
        public virtual DbSet<TBL_Hobby> TBL_Hobby { get; set; }
        public virtual DbSet<TBL_Skills> TBL_Skills { get; set; }
        public virtual DbSet<TBL_SocialMedia> TBL_SocialMedia { get; set; }
        public virtual DbSet<TBL_TodoList> TBL_TodoList { get; set; }
    }
}
